
```{r}
library(ggplot2)
library(tidyverse)
library(Quandl)
library(dplyr)
library(readxl)
```

```{r}
library(readxl)
producao <- read_excel("C:/Users/Usuario/Downloads/IPMAN.xls", 
    skip = 10)

emprego <- read_excel("C:/Users/Usuario/Downloads/MANEMP.xls", 
    skip = 10)
colnames(producao)[1] <- "date"
colnames(emprego)[1] <- "date"
colnames(producao)[2] <- "value"
colnames(emprego)[2] <- "value"

dados = merge(emprego,producao, by="date")

```

```{r}
plot1 <- ggplot(data=dados)+geom_line(mapping=aes(x=date,y=value.x))+ggtitle("Emprego na indústria \n") +  xlab("Date") + ylab("Empregos")

plot1
```

```{r}
plot2 <- ggplot(data=dados)+geom_line(mapping=aes(x=date,y=value.y))+ggtitle("Producao Industrial \n") +  xlab("Date") + ylab("Producao")

plot2
```


```{r}
dados <- mutate(dados, pchange.x = ((value.x/lag(value.x) - 1)))
dados <- mutate(dados, pchange.y = ((value.y/lag(value.y) - 1)))

plot3 <- ggplot(data=dados)+geom_line(aes(x=date,y=pchange.x), color= "red")+geom_line(aes(x=date,y=pchange.y), color="blue")+ ylab("variacao percentual")
plot3 
```

```{r}
plot4 <- ggplot(data=dados)+geom_density(aes(pchange.x), fill="red",alpha=0.5)+geom_density(aes(pchange.y), fill="blue",alpha=0.5)+ xlab("x") + ylab("density")
plot4
```
```{r}
plot5 <- ggplot(data=dados)+geom_jitter(aes(x=pchange.x,y=pchange.y)) + xlab("variacao empregos") + ylab ("variacao producao")
plot5
``` 

